version: 0.2

phases:
  install:
    commands:
      - echo Executing Intall Phase
      - echo Executing second part of Install Phase
    finally:
      - echo Executing Install Finally

  pre_build:
    commands:
      - echo Executing Pre Build Phase
      - zip -r deploy.zip .
    finally:
      - echo Executing Pre Build Phase

  build:
    commands:
      - echo Executing Build Phase
    finally:
      - echo Executing Build Finally
  post_build:
    commands:
      - echo Executing Post Build Phase
      - aws s3 cp deploy.zip s3://fghbjnmk
    finally:
      - echo Executing Post Build Finally 
